name: Package and Deploy

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install

      - name: Package
        run: make package

      - name: Publish
        run: make publish-test
